apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:pe/Vbg3cdRTQaX0Dn3SJGeAmAK4hCNg02FevRSaYy/h9+t4KNOIWhg==,iv:ZSTLNVIeDHJQvh3mh7Jkp31dFyc07EhKTtR1j01l1SU=,tag:dbWZXNPKDsxmaNc2bXUggg==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T19:46:21Z"
    mac: ENC[AES256_GCM,data:h38FAQLb4cSmvxx/tBaSfDcm7tY8bBa3WMruOsr6eoMoAZ3u4ikCR2Gba9qpMVlVAsgXRN0oNmS35BiXIJD82JBkp4e6lhJFEnleoIWLMFz3VQsC14DSKdQeTjzmLaAGLLNHxFMdB34WLs50+UWBee0IW2WduIqr7Vymet/DmKw=,iv:mDlZsWQINkTW1Dq17oKUH1Y7OXUwi692bincAA0rRKM=,tag:8vHLE8QUkxIalpZowdM2RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
