---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - cilium.yaml
  - intel-charts.yaml
  - jetstack.yaml
  - longhorn.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
