apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:UcpU624TZOPRefViAw7M8Q==,iv:RuiW4n3SUZuJd43J1OUMAgxk0N4aQwlvHwN7LIoXrts=,tag:FXJKZl94KMqEM3Swl5v1cA==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T20:11:22Z"
    mac: ENC[AES256_GCM,data:BsJYwKVmoH1TnNXRWUORSvfbXJoTNnaStHpeT+OpvMtSqzScf7/xdYzFX/fy0s0kaTetmLUu1uQ2C18ESc5ey/Ll4z0gPwPAWN1z1x3vD3wvordhEEoxyPpc1OS3tBduSXRJEi//KwYiEMGPPEUUoIi2g1uWqnWT4LD4Cx/cWxY=,iv:A6RmZOEiEBpkL2MsN+cJKcwEY4vthx3eBRSOKLj3oLk=,tag:W9LOKXDS02q8XhuF7H827w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
