apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:6XJJqlL61HNELtz2,iv:68owvGqnWxGX8C4lx/9w3WaGivHJweIZA/WnF8cdHq4=,tag:gpIMx7bdLQVkZqskARxy3A==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T21:25:31Z"
    mac: ENC[AES256_GCM,data:0zT1rUSm24/EGUSJeQXMB+dBHOSTuE92wcpCKw5JfnPnRjqHNjP51f5JHdgthEbTtomY3Om5wAH6AFCVmrt0DnZLNtyjkyx0DfV1xxNIYD9itzOgxliUDf+kzmbC8DIQy1fpkTP8TguKRYvQIcmHdIeOzdKTbuKtmeDVSnKgPNI=,iv:NXnzTTY17Q1emIblUDnbXlSD8odrpgvCl0g/jz12Vpg=,tag:dImsf0UZ6OBKlly/QsLNMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
