apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: flux-system
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:EgYbyHId,iv:ipfE2gCklciFTdoHDCVlPG3R62ir+RuPO91jo6SB3iw=,tag:9AsqaFTuhWxwuEArWqhd/w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uMHzvg7ssU4UBLjmRM7/+rNIMMs=,iv:YaaSZ7+FDePhioIlVMve8jZqgVHPeGQ+Mrw+tmgGh8g=,tag:2YOijOAZytmeW2hVWnXdcA==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:g+nuInrbKeubu7k+IGTce3T0D4D+wCtjyFtS7GdeRVX9ZNZpbK8x,iv:/dvLKRCbZvX6N5pnqdySDD0eh5FcVyfluelcuon5JYY=,tag:FPv485A4DxROlx8eYsmzMQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:BZ9ZCA==,iv:cE9wJWwB5Ygb7XCi1grrPfcyqgYjikRI4DxkGg+18pg=,tag:SCa1OT49P/CElu55MxDSoA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:7CWfTrLQ,iv:coNghjDl0Baa+kpDlexi4tvu11YLSyyay8nP4x7jJ30=,tag:aDDcimCeExMTXBWEfX3MTQ==,type:str]
    DB_ENGINE: ENC[AES256_GCM,data:nP/kIi99Aco=,iv:5USULyR8hctshJ3oZ0HSLCybT9xBhskQUehNrVrjTPU=,tag:2Mxeg3ntxMSgz3iR0sxRcw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZD9329Iw,iv:Ei/YElVfCkHsLmM4WmMZp2R3kzAEG2hZGMY/29xo1f0=,tag:2COlyFP4Xhqfm2gMsZJBiQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:YcdrhANWhn7iAdKAOWIyhUmsCZDmYlSUmefFPf3VWXK4vzGSR3RS,iv:FlTV4yt02HBJAgQm5Kr4Q5Ykl8fD+LoIADJNF6fKBrg=,tag:zI19Oi62gI0zOOB0NChh5g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:n4dYVcZY,iv:LOoIctw2zCq7qeYW7ixgT1ZSHgIYm9ZqmTmmFvxN2AM=,tag:kG3gRPa9a06eVms47mMPjw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sUirkQnXrGowuadXLYVK+CrFnv4=,iv:QeinLh57Er8B0lTzhTwJLAXanw7sJdEJhKkl1N/kjjc=,tag:x92VbF6xxGNeCFHyY19yzw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:oAtquv7+TfX+MdYnmSH5FK7zkmc=,iv:XWlKvzDgJGKSRwZPSDfqE4a4rM/S4di7Nn56RiAuINk=,tag:8A9vEJNQc1NJK7rSiVOkWA==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T16:03:24Z"
    mac: ENC[AES256_GCM,data:x1ZWJ22Ap0spw0BhtRH4nAqvDVIy7LYMDjer94NjQRW2aUh+kDussqkhcBTGhUBfklulXsLZ5YOy/e7zJ0ahQOLjqCmzB8jb09FtVv77oEOW+/pnlDvrIrEkUHLEn3mUyW0vhtWIUF6LE3f3tINBySlky8gcZq/hz5AAj9iFn1U=,iv:OaDWThCb/hGdhEe8RSH5U033ALpw5ARr97UuTG3cRmc=,tag:kfWv8YzkluCTZ9mgpNl0zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
