apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: flux-system
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:R1Run1C7VTjhCNGBwK6FI2o7XAB4qUFiCOfjtOC7k/U=,iv:lGygThvRKU4r1UYxcyOl8itKfXIFRGLxlXj3gJk/uyQ=,tag:qK2pWYSEQ/uuWAIzJuFFiA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:/9928lGR+Ihumg6ECfVwIMa/7iKKEbKzlZMtC8Pevaw=,iv:2E38L0Yayfi3+BrzUKn7AuaLoz5AUSc4xJD1u4Hh+qQ=,tag:HRbxMCelyHwb6cQLGP0dFA==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:53:02Z"
    mac: ENC[AES256_GCM,data:UJDaDsHTtz1guWGABqHK3QBwSZbgJgYeyegSpU5w62fL0QokKPDFzEgzxt2Y8rzO3eEkYwvj9UTTrO4dtR/Kky/XFDKHpR3dK10nirMpNkzyRlRaSq17Y95Px6zkMYL1mMbAp0iMTOFiDERQv8lFl1VJNhZ9f2iId+GQqpAcPTQ=,iv:9Cxy645Q8sYxxK78W6zlMdlR6wLnEXs8GI79QgmcRC0=,tag:xGlPfQykzCY3y/J1WNzfnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
