apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: flux-system
stringData:
    admin-user: ENC[AES256_GCM,data:7wILWeE=,iv:W7u1Yo3SEQuMtESfpLkgKpKWuLSJc14DrFHzGadJP5E=,tag:kXhkbtDIOsTLSfvLq4Od0g==,type:str]
    admin-password: ENC[AES256_GCM,data:ryv/b3I=,iv:SPv1nhRQChiJtxNrfpkn74dBt7Ji5G0svOlNbOeTqms=,tag:DzojclLmcx+AF8h0Ax45hA==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T22:53:36Z"
    mac: ENC[AES256_GCM,data:NfK6HOy60WLURukvc2WMTsCGoCNar6LnQBEzRroMdELXg2DYQ/MkHcYv3UoIyxhAEP9Z60PXrFe86wWZC95hM5qk5QoFfEuYXEr32Q3RCPX8y5rq5w4iOOME3AZ4d4HqcQywtvmAfUsecZJNCcDCOq97URBmiEUk0tvAFteOkl0=,iv:URRU1bJWhJnbmDFSOluleku2G1WsHJU0MKUISdUQpjQ=,tag:RyZDsOJ2K4zwVFTDKH8x3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
