apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: flux-system
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:9PpAcp9Qj4JJolyXYEXnG9WXIBG0pfNA/0soMTbUy/4=,iv:tSjD1QrBrN5Avy1MusqeJH0BPAI1w7Px33mSocmUFdA=,tag:Y4Y+S4SAVKsBmuwGhP28VQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:30:47Z"
    mac: ENC[AES256_GCM,data:jrX9f34VKussKo49EkwIP1mu/1PmUAJAouxKJYlL6F2PvXJJSf8uS4faGiAKINUsHI1ZFoTvbhP9bfSjyI9jWOQjzUJmawng4BkLt7NN4ob28m+VpuxLRC5r6Ros+tuMNagGe6631HNAOhUBGRa03KuNrdgEqANRKDO1ocg2f4M=,iv:gMVoeOlwrBoHUeL9XFQUdNWTeNEW5UWfj6lMNAyg3qk=,tag:Qz9FN3s9T2Mh0TxWbyNQow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
