---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN/./-}-production"
spec:
  secretName: "${DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN}"
  dnsNames: ["${DOMAIN}", "*.${DOMAIN}"]
