apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: flux-system
stringData:
    api-token: ENC[AES256_GCM,data:BOlmjY8OXq4XThklTU8GpTXZn1muc6FPkKxR0uNEO6oBGxV/qhDQng==,iv:Ejv7OI699aFqGJF8naTifR3OiYxBgB3a72UGttuozzs=,tag:Hhf7LM2aLQ/ik9x/GcGR7A==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T20:33:19Z"
    mac: ENC[AES256_GCM,data:f9uU/g/pwAfbVOkTQ4jnEZC+1VKnGWUCR4O6ACTk7LNNcskWoPhC8TKgmTd8/99PSegTmwB9gAYA5VCnKQmIpsYQR+G/3tLE98gQNEOAg4MMWoEb6wTjzc2oWPDJBR482Tv0ewawm4UGWrBIhP7xGcNR8YrFx+ePAgkixb/0X7w=,iv:WmleKdEJ9lILvwVAVCOo2HUr3Tty463VSIUool4jL6o=,tag:VglExWdfS5AkhSFNaOeHhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
