apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secrets
    namespace: flux-system
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:z/FM/mOaIGxJUlj5FmYdl57EfNIn1fR7QDlk0fVwYKo=,iv:EkA6XnbYHIjLGnoGZXoSYkQMl4SsBY/48rT+D7jlmEQ=,tag:VYj7IeqrkJ4vtk8hTgYlZg==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:34:38Z"
    mac: ENC[AES256_GCM,data:NOrrL2cgrfR7LtYlxzCPW4F7hfT4bXn5ZvWvG2c4QUDNNkYCPSDfoIgJeIv2j6WMdeDPg6/J7B8TONEShVukDG989rIv+jvvXAQZ7rgqKVR6Fcgj7hGo065NY7jHpkOZhOkKEys44ns41bQzf2ZNB7jytYmlgRPrpRX9sO7OyTQ=,iv:Z2kkFylPaZHU4Vt+dksg3wHtcmZLv5UcGiii0P3b2NA=,tag:uFTxldwzySCDsZFgeZXMug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
