apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: flux-system
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:eyr9CcMbDa2tTOMPfvUaYQ/hucP1Tjau/vJDWW5Yh80=,iv:IOQqxTdBVKZyO/qv5ne0wiXf40dIUfh65emDiZ+qh3o=,tag:7Y635QE9q1jc3U11IWSIkw==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T19:31:57Z"
    mac: ENC[AES256_GCM,data:WCEZhJX/rx/ASnoIk3YwvmoAZCwkujAP8rwvNJB4enqUs5hXuzSKk0UaZuwznTbeZmygMzrlIS/atm7XtSs6llK9Lt9RpIJDTUT/YHscu7PnIoaLGjTqJfcOtV1yeleRoJ8au4hkY0FuCqiojvb2nXi8Y/zRClwbPSiCHloioQk=,iv:pZUSQJ+Bk1q5ysSH2kE+KwM3TBuQuLzWND268JkMedM=,tag:9RB8HFfQrEVJftPM/zTHAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
