apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: flux-system
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:onvEl4+XGVmHCQOb9VEYar9yWs27mTJLeGYyiCyrIZI=,iv:SKmYPxVVCURHCuRxcJy+Qy/MFHqpe0LDb9EYYdCTodM=,tag:St/OLo5CFUOfp3ZbZXnOJQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T17:47:40Z"
    mac: ENC[AES256_GCM,data:kg/My7TXFa6X/jBvNBw3ue9GEo7rXqCjg8J2UmY+LpRF4GlG549fh0d15+lnVfhg6IJwPGS0eH0gcuvKQqR+rkfF5d26msnrQbW8G98se5IWcgWqxBOrJe7rNHrS/J+P7zIiWGBBrtq9uoaqm+XgbWO9Vd7dTnA/d0y4wSh3AVE=,iv:HBadFJUQ25z8fUsu3mvftTp9nhdw+PJBFe3MejFEpis=,tag:q4RUeLhKuZVS8n/2kJJeRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
